# bit build and test CI

name: Bit build and test CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [main, develop]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  bit-build-and-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-bit-ci')"
    env:
      BIT_TOKEN: ${{ secrets.BIT_TOKEN }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install dependencies and build app
      - name: init bit.dev
        run: |
          echo "Adding bit.dev to npm registry"
          npm config set @bit:registry https://node.bit.dev
          npm config set //node.bit.dev/:_authToken ${BIT_TOKEN}
          npm config set always-auth=true
          echo "Completed adding bit.dev to npm registry"
        env:
          BIT_TOKEN: ${{ secrets.BIT_TOKEN }}
      
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install Bit Version Manager 
        run: npm i -g @teambit/bvm
      - name: Install stable Bit version 
        run: bvm install
      - name: add bvm bin folder to path
        run: echo "$HOME/bin" >> $GITHUB_PATH
      - name: Set up bit config
        run: |
            bit config set analytics_reporting false
            bit config set anonymous_reporting false
            bit config set user.token $BIT_TOKEN
      - name: Install packages using bit
        run: |
            cd workspace
            bit install
      - name: Build components
        run: |
            cd workspace
            bit compile
      - name: Test components
        run: |
            cd workspace
            bit test
